# name: Deploy main

# on:
#   push:
#     branches:
#     - main

# jobs:
#   build:
#     name: Deploy main
#     runs-on: ubuntu-latest
#     steps:
#       - name: cURL request
#         # Hit the webhook endpoint to rebuild  from the "main" branch
#         run: curl -X POST [vercel deploy hook 주소]
